on:
  schedule:
    # “At 15:15 on day-of-month 15 every month.”
    - cron: '15 15 15 * *'
  workflow_dispatch:

name: archive_nflversedata

jobs:
  update_snap_counts:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            ropensci/piggyback
            pkgload
            nflverse/nflreadr

      - name: Archive all nflverse data
        run: Rscript -e 'source("dev/run_archive.R")'
