on:
  schedule:
    # At 15:15 on Thursdays every week in Sep - Jan
    - cron: '15 15 * 9-12,1 4'
    # At 15:15 on the 15th day of each month from Feb -> Aug
    - cron: '15 15 15 2-8 *'
  workflow_dispatch:

name: archive_nflversedata

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: create_release
    env: 
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - name: Create release with gh
        run: gh release create archive-$(date '+%Y-%m-%d') -R nflverse/nflverse-data-archives
    
  archive_nflversedata:
    needs: create_release
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04,   r: 'release'}
        tag:
          - combine
          - contracts
          - depth_charts
          - draft_picks
          - espn_data
          - ftn_charting
          - injuries
          - misc
          - nextgen_stats
          - officials
          - pbp
          - pbp_participation
          - pfr_advstats
          - player_stats
          - players
          - players_components
          - rosters
          - snap_counts
          # - test
          - weekly_rosters
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NFLVERSE_ARCHIVE_TAG: ${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            ropensci/piggyback
            r-lib/pkgload
            nflverse/nflreadr

      - name: Archive nflverse release
        run: Rscript -e "source('dev/run_archive.R')"
